### ISSUE TITLE
Basic auth doesn't work

### ISSUE THREAD

**Issue by mderazon** [IBM/couchbackup#689]
### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue
(instance url and credentials are made up, but similar in syntax)
```sh
$ npx @cloudant/couchbackup -u https://252e97cd-89fc-4c90-83c5-de6a2ffc6d74:0f74a8b6-cd15-41d3-b267-011eff6bd64b@couch-prod.example.com -d 4dd052f3-f049-4eb2-a022-93ea5930cbe7
```
Getting

> ERROR: Access is denied due to invalid credentials.

However, cURL with the same username/password:
```sh
$ curl https://252e97cd-89fc-4c90-83c5-de6a2ffc6d74:0f74a8b6-cd15-41d3-b267-011eff6bd64b@couch-prod.example.com/4dd052f3-f049-4eb2-a022-93ea5930cbe7
```
Works okay:
```json
{
  "db_name": "4dd052f3-f049-4eb2-a022-93ea5930cbe7",
  "doc_count": 5122,
  "doc_del_count": 957,
  "update_seq": 14962,
  "purge_seq": 0,
  "compact_running": false,
  "disk_size": 6709370,
  "data_size": 5726002,
  "instance_start_time": "1705060479540775",
  "disk_format_version": 6,
  "committed_update_seq": 14962
}
```

DB version:
```sh
$ curl https://252e97cd-89fc-4c90-83c5-de6a2ffc6d74:0f74a8b6-cd15-41d3-b267-011eff6bd64b@couch-prod.example.com
```
Response:
```json
{
  "couchdb": "Welcome",
  "uuid": "88930564-c51c-46c6-8764-82bbae57998b",
  "version": "1.7.2",
  "vendor": { "version": "1.7.2", "name": "The Apache Software Foundation" }
}
```

### 2. What you expected to happen
To work

### 3. What actually happened
> ERROR: Access is denied due to invalid credentials.

## Environment details

- Version(s) that are affected by this issue.
    2.9.16
- Node.js version
    v21.1.0

**Comment by mojito317** [comment]
Hi @mderazon!

The [minimum required CouchDB version is 2.0.0](https://github.com/IBM/couchbackup?tab=readme-ov-file#requirements). I see from your DB version, it is under 2.x.

While the error message is a bit confusing, the real problem here is Couchbackup uses session cookies, so under the minimum required CouchDB version, this cannot happen.

Be aware if you have special characters, you should encode it with percent encoding, as our documentation highlights it: https://github.com/IBM/couchbackup?tab=readme-ov-file#the-url

I see 2 options you have here:
1. It might be possible to use shallow mode from such old CouchDB version if you allow to get a session cookie.
2. The other option for you would be copying the db file from the old database to your new one.

**Comment by mderazon** [comment]
I see, thanks for the answer!

**Comment by ricellis** [comment]
See also https://github.com/IBM/couchbackup/issues/334#issuecomment-641098496

CouchDB 2 is the first version with `_bulk_get` which is used by the full backup mode. Shallow backup uses `_all_docs` so could potentially work if the CouchDB is configured to allow `_session` requests.
